name: ssh
on: workflow_dispatch

    
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - uses: actions/checkout@v1
 
    - name: goorm
      run: |
        sudo apt update
        echo -e "${{ secrets.PASSWD }}\n${{ secrets.PASSWD }}" | sudo passwd runner
        curl -s https://install.zerotier.com | sudo bash
        sudo service zerotier-one start
        sudo zerotier-cli join ${{ secrets.ID }}
        cd ~
        sudo apt update
        sudo pip install selenium
        sudo pip install requests
        sudo pip install lxml
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -zxvf geckodriver-v0.30.0-linux64.tar.gz
        sudo mv geckodriver /usr/bin
        wget https://github.com/aaaaaaction/abouttab/releases/download/v9.99/frp.py
        echo ${{ secrets.GOORM_URL }} > url.txt
        echo ${{ secrets.FRP_TOKEN }} > token.txt
        
       
    - name: docker
      run: |
        cd ~
        sudo apt update
        sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        sudo docker run --name mcser -d  ${{ secrets.DOCKER_MCSER }} sleep 9999999
        wget https://github.com/fatedier/frp/releases/download/v0.41.0/frp_0.41.0_linux_amd64.tar.gz
        tar -zxvf frp_0.41.0_linux_amd64.tar.gz
        mv frp_0.41.0_linux_amd64 frp
        cd frp
        rm frpc.ini
        mv ../pw.txt .
        mv ../em.txt .
        mv ../url.txt .
        mv ../token.txt .
        mv ../frp.py .
        sudo nohup python frp.py &
        cd ~
        sudo docker cp mcser:/root/mc .
        sudo docker stop mcser
        wget https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_linux-x64_bin.tar.gz
        tar -zxvf openjdk-17.0.2_linux-x64_bin.tar.gz
        mv jdk-17.0.2 jdk
        cd mc
        sudo wget https://github.com/aaaaaaction/abouttab/releases/download/v9.99/server.py
        sudo python server.py
        sudo rm server.py
        cd ..
        echo -e "FROM ubuntu:latest\nCOPY mc /root/mc" > Dockerfile
        cd ..
        sudo docker build -t ${{ secrets.DOCKER_MCSER }} runner
        sudo docker push ${{ secrets.DOCKER_MCSER }}
        sudo reboot
      



